### ISSUE TITLE
How to incorporate units into an array

### ISSUE THREAD

**Issue by BenGassaway** [monroews/CEE4530#10]
Our group had to incorporate the theta value into the file itself 'Lab3AcidRain_bestdata.csv' because array could not handle units during multiplication. Please let me know what is the best way to directly incorporate units into an array for the Atom python script. Thanks!

**Comment by monroews** [comment]
Use numpy functions to handle arrays. numpy is unit friendly.
````Python
time = np.linspace(2,10,5)*u.s
distance = np.linspace(5,10,5)*u.m
velocity=distance/time
velocity
````

gives this as the resulting matrix
\[\begin{pmatrix}2.5 & 1.5625 & 1.25 & 1.09375 & 1.0\end{pmatrix} meter/second\]
