### ISSUE TITLE
Equation 45 in lab textbook

### ISSUE THREAD

**Issue by rosiekrasnoff** [monroews/CEE4530#102]
equation 45 here: https://monroews.github.io/EnvEngLabTextbook/Acid_Neutralizing_Capacity/Acid_Neutralizing_Capacity.html#equation-eq-gran-ph-lt4

 is missing a negative sign, it should be ANC= -[H+] , instead of ANC= [H+] that is currently there.

**Comment by monroews** [comment]
fixed in release 0.0.24!
