### ISSUE TITLE
Cannot download aide_design to local hard drive with pip install

### ISSUE THREAD

**Issue by BenGassaway** [monroews/CEE4530#11]
For a PC: Does anyone know how to address this issue? No matter what I do, I cannot download aide_design to my computer. In atom, it pops up with the error message posted below. Whether I use pip install on Anaconda Prompt or my Command Prompt, it still will not recognize "pip" as an internal or external batch command. Can't find anything online. Otherwise, I'll just use the computers on campus. Thanks!
![image](https://user-images.githubusercontent.com/31353222/36177965-6c39a138-10e5-11e8-8147-72e95fed5055.png)

**Comment by cc2467** [comment]
Does [this link](https://stackoverflow.com/questions/23708898/pip-is-not-recognized-as-an-internal-or-external-command) help at all?
