### ISSUE TITLE
atom packages failing when atom opens

### ISSUE THREAD

**Issue by caj92** [monroews/CEE4530#117]
these messages appear when I open Atom. I am not sure if I need the things they refer to, but they did not use to appear.
![image](https://user-images.githubusercontent.com/46975010/54144484-32896800-4402-11e9-8594-ef679f33a03b.png)

**Comment by JonathanDavidHarris** [comment]
I would update the atom packages, they're probably out of date which leads to these errors.

**Comment by caj92** [comment]
after updating everything, and restarting atom, the issues are still there.

**Comment by monroews** [comment]
Does Atom do what you need it to do? 
I recommend uninstalling those two packages and then installing them again.
