### ISSUE TITLE
Invalid Syntax Error 

### ISSUE THREAD

**Issue by SungMinKim2795** [monroews/CEE4530#12]
I have been getting issues with the ``` ending of a python block when defining functions, regardless of the code inside. I shift enter the line of "def ....." and then an error pops up at the bottom of the file, not underneath the code block, saying invalid syntax. 
Has anyone had this issue before? If so, what should I do? 
I was told to @ethan92429

**Comment by cc2467** [comment]
Can you try highlighting the exact code you want to run and use Hydrogen to run it? (instead of pressing shift+enter?)
