### ISSUE TITLE
Curve fitting

### ISSUE THREAD

**Issue by lw583** [monroews/CEE4530#128]
I used Excel to find a curve that fit nicely with the first 6 points and plotted another line to plot the last few (which all have values of 0). This was a polynomial (to the power of x**4), which only works empirically to fit this data. Since there is not much explanation for why this is the case, should I...
1) Leave it as it is and just explain that it was the curve that fit best
2) Not put a curve at all because I do not know how to explain the model?
Thank you!
<img width="477" alt="Screenshot 2019-05-10 at 5 01 39 PM" src="https://user-images.githubusercontent.com/46941988/57556521-4ccdbc80-7345-11e9-981d-ce59dc83dad8.png">

**Comment by lw583** [comment]
Similarly for here (which is volume of water treated for the first 6 experiments shown above), should we be using a linear fit or a logarithmic fit? The logarithmic fit looks nicer but again, I cannot justify any of the results.
<img width="716" alt="Screenshot 2019-05-10 at 5 27 40 PM" src="https://user-images.githubusercontent.com/46941988/57557647-ee0a4200-7348-11e9-946a-f9e0fd6d01c8.png">

**Comment by monroews** [comment]
It is fine to explain what you said in your question.  The curve fit
doesn't make sense,  and it shows the data trend nicely.  This is great
data and you can try to develop an explanation!

**Comment by monroews** [comment]
Consider using time/hydraulic residence time on the y axis of the first
graph

**Comment by lw583** [comment]
I plotted it with the normalized time but decided to keep it just as time because I also have a graph of volume treated, which looks almost exactly the same as the one with normalized time! I wanted to show what it looked like before and after normalization in my analysis. Hope that is a good enough reason. Thanks!
