### ISSUE TITLE
Making a legend

### ISSUE THREAD

**Issue by leahbalkin** [monroews/CEE4530#17]
What code should we use to make a legend on a plot? I've been looking at https://matplotlib.org/users/legend_guide.html for help but haven't had any success

**Comment by jdh345** [comment]
plt.plot(x,y,label = 'this is my label')
plt.legend()
plt.show()

**Comment by ClaytonSasaki** [comment]
2 more helpful things about legends:
- loc='SOME LOCATION' OR bbox_to_anchor=(FLOAT, FLOAT)
- borderaxespad=FLOAT

ex.
plt.legend(loc='upper right', borderaxespad=1.)

OR

plt.legend(bbox_to_anchor=(0.95, 1), borderaxespad=1.)

The loc and bbox_to_anchor set the location of the legend and borderaxespad gives a padding between the axes and the legend.

More can be found here: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.legend.html
