### ISSUE TITLE
Suddenly unable to run created functions or for loops

### ISSUE THREAD

**Issue by hispanicberniebro** [monroews/CEE4530#18]
My Atom updated upon opening it today and I tried running functions such as alpha0_carbonate but given an error pointing to the ``` syntax at the end of the block of python code getting this error message:

Anyone else getting this as of now?

File "<ipython-input-57-384cce1344ab>", line 24
    ```
    ^
SyntaxError: invalid syntax

**Comment by cc2467** [comment]
Can you try highlighting the exact code you want to run and use Hydrogen to run it? (instead of pressing shift+enter?)

Or closing atom and restarting?
