### ISSUE TITLE
Prelab 5 Question 3 

### ISSUE THREAD

**Issue by JonathanCTsang** [monroews/CEE4530#19]
For question 3 on Prelab 5, it says to use Excel to plot a graph of t vs E. Can we use Excel to make this plot or are we supposed to do it on Python?

**Comment by cc2467** [comment]
Please use Python, apologies for the typo

**Comment by monroews** [comment]
Check the new [syllabus](https://confluence.cornell.edu/display/cee4530/Syllabus). I've adjusted the syllabus to give us more time to develop good data analysis methods in python.
