### ISSUE TITLE
"user could not be spawned" error?

### ISSUE THREAD

**Issue by lilyfalk** [monroews/CEE4530#22]
<img width="1078" alt="screen shot 2018-02-24 at 2 39 23 pm" src="https://user-images.githubusercontent.com/35751737/36634314-a8bab79e-1970-11e8-93fd-d2dc1d164074.png">

Has anyone else gotten this error or know how to fix it?

**Comment by cc2467** [comment]
Hi Lily, 

Can you try running Atom from your terminal instead of through the start menu/apps bar? Just type in `atom` to your terminal or anaconda prompt and it should open. 

Maybe [this link ](https://atom.io/packages/script)will help.
