### ISSUE TITLE
Graphing Axis Issues

### ISSUE THREAD

**Issue by knichols1284** [monroews/CEE4530#23]
When my team creates a graph for our 5 data points for lab 4, the y axis does not increase at a constant interval. Instead, each horizontal line of the graph takes a value of one of the data points so that it appears as a straight line when it really should not. Below is the code we used to make the graph and a screenshot of the graph.  We are also confused about how to add a legend, and how to label regions of the graph for #1.
For #3 we are not sure how to plot our 5 data points on a graph with the very large arrays from Lab 3. Thanks for the help

pHsample1time0 = (sample1time0[7:18,1])
titrantvolsample1time0 = (sample1time0[7:18,0])
plt.plot(titrantvolsample1time0,pHsample1time0)
plt.xlabel('Titrant Volume', fontsize=15)
plt.ylabel('pH', fontsize=15)
plt.show()

![anc_graph](https://user-images.githubusercontent.com/35776812/36707691-5c5111ae-1b3d-11e8-8e1d-4ac7806c08cd.PNG)

**Comment by monroews** [comment]
The problem here is that the array that you are sending to matplotlib is an array of strings rather than an array of numbers.
