### ISSUE TITLE
Error With EPA.ftime Function

### ISSUE THREAD

**Issue by JonathanCTsang** [monroews/CEE4530#24]
When I try to use the EPA.ftime function to grab the time data from my data file, I get the error "unable to parse string "0.599381007,8.005178452" at position 0". Do I need to make an array for this function or is there some other function I'm missing? Also what units does this function return time in?

**Comment by monroews** [comment]
The EPA.ftime function is expecting the tab delimited data file that was created by ProCoDA. It appears that you are sending a comma delimited file to EPA.ftime rather than the original tab delimited file. Use the original file from ProCoDA.
