### ISSUE TITLE
Plotting ANC+ graph labeling - Lab #4

### ISSUE THREAD

**Issue by Ajara-C** [monroews/CEE4530#29]
How to label a curve with multiple "regions".
In the ANC lab questions we are asked to "Label the 2 regions of the graph where pH changes slowly with the dominant reaction that is occurring. (Place labels with the chemical reactions on the graph in the pH regions where each reaction is occurring). " We know how to do a regular legend, but how would we get two labels for one curve?

**Comment by monroews** [comment]
There are several options. 

1. annote the graph. See https://matplotlib.org/users/annotations.html. 
1. Split the plot into segments and use different colors for each segment. This will make it possible to label the segments in the legend.
