### ISSUE TITLE
www.I don't feel like googling this.jpeg

### ISSUE THREAD

**Issue by simonfines** [monroews/CEE4530#30]
How do you call certain rows in an array? Like if I wanna call rows 4-18 of the first column of an array.

**Comment by hjh57** [comment]
name_of_array[4:18,:]

**Comment by simonfines** [comment]
OMG THANK YOU!!

**Comment by carmenou28** [comment]
If you want to get technical, it'd actually be name_of_array[3:17,0] since indices start from 0 in python, and you're only calling the first column of the array instead of all columns of rows 4-18.

**Comment by simonfines** [comment]
Oh yeah I forgot about that format. Thanks!!!
