### ISSUE TITLE
Still Can't Import Data from Files?

### ISSUE THREAD

**Issue by kla67** [monroews/CEE4530#31]
When I use the same line of code as the rest of my group (file= pd.read_csv('Lab3_Data1.csv')), and have the file that I'm trying to pull data from saved in the same folder, it says the file can't be found. I don't have a mac, if anyone has had a similar issue!

**Comment by simonfines** [comment]
Is this on the shared code through a portal or on a separate individual code?

**Comment by kla67** [comment]
@simonfines I've tried it on both and neither have worked. @jdh345 that worked!! Thank you so much
