### ISSUE TITLE
Running function defining lines in atom

### ISSUE THREAD

**Issue by lucindali** [monroews/CEE4530#32]
I was having a lot of problems with running a line of python code to define a function. If you are too, you might want to highlight all the lines of code used to define your function and then click shit+enter because atom will stop running code up to the line you click shit+enter on.

**Comment by monroews** [comment]
You can also place your cursor at the beginning of the line that starts with "def". Shift+enter will cause the function to run. Of course, no output is generated because all you did was define the function.
