### ISSUE TITLE
Clarification on assignments due Monday

### ISSUE THREAD

**Issue by ericamarroquin** [monroews/CEE4530#38]
Both the Acid Rain and ANC labs are due on Monday. Should they be two separate reports? 

The ANC lab has a "+" next to it, thus it needs to be a full report. There is no "+" or "-" next to the Acid Rain portion in the syllabus. Is this a full report as well, or just an analysis in Atom?

In the future, I think it would be helpful if the syllabus was updated with more clarity and detail on assignments. Or, at least an issue posted on Github making everything clearer. It seems that a lot of things pertaining to assignments are said in class, but not posted online for everyone to see and review. It is creating a disconnect between students, and I can say I am not the only one who is confused about assignments.

**Comment by amr385** [comment]
i am under the impression that we are to write one combined report for both of them as they are related.
