### ISSUE TITLE
Single point will not align with the y-axis

### ISSUE THREAD

**Issue by BenGassaway** [monroews/CEE4530#42]
Hi! We have tried plotting the value produced by our slope function, and have even tried hard coding a value for y, but it still does not align with the graph. Has anyone had similar troubles? I have posted our code and graph below. Thanks!

![image](https://user-images.githubusercontent.com/31353222/36926990-b0edbc5e-1e48-11e8-9f81-f6d0ebde454e.png)

![image](https://user-images.githubusercontent.com/31353222/36927002-c2dfbcd2-1e48-11e8-94f2-fe226e2574a5.png)

**Comment by monroews** [comment]
Did you try the code that I provided in [ANC_analysis.md](https://github.com/monroews/CEE4530/blob/master/ANC_analysis.md)? I create a pair of points that define the end points of the line that I want to draw and then send those points to matplotlib where it automatically connects them with a straight line.

**Comment by monroews** [comment]
The fundamental reason why your code is not working is that the values that are being sent to matplotlib are text strings and not numbers.  You can see this by the fact that the y axis labels is just a list of the strings for the y values.
