### ISSUE TITLE
Linear Regression on Gran Plot

### ISSUE THREAD

**Issue by sh787** [monroews/CEE4530#43]
Still tryna use the code from the ANC file

![bitmoji](https://render.bitstrips.com/v2/cpanel/02681f5c-0dd5-4cff-a55a-495ad73f61f7-21a46ef2-0a6f-41b8-9fa6-b30ab069bb94-v1.png?transparent=1&palette=1&width=246)

**Comment by monroews** [comment]
Provide the code that you are trying to use. Explain what steps you have taken to try to get it to work.
Show the error that is generated from running the code.
