### ISSUE TITLE
Will we get Acid Rain/ANC lab report back before next full lab report due?

### ISSUE THREAD

**Issue by Megan-McE** [monroews/CEE4530#50]
The full report for the Reactors Lab is due Friday, but will we have the Acid Rain/ANC lab graded before then? I ask because it would be very helpful to know what we did right/wrong/how you are grading them to ensure improvement of this report. Thanks!

**Comment by Megan-McE** [comment]
Wow, good question.
I would also like to know the anser

**Comment by jillianwhiting** [comment]
We are trying to get it back by then but we cant guarantee we will finish grading by then

**Comment by Megan-McE** [comment]
thank you!
