### ISSUE TITLE
Solver code needs to be updated

### ISSUE THREAD

**Issue by leahbalkin** [monroews/CEE4530#54]
Currently we are trying to run the EPA.Solver_AD_PE code for number 1 on the lab report. Here is our code: AD2 = EPA.Solver_AD_Pe(time_data2, concentration_data2, theta, C_bar)

And here is the error that keeps popping up: /Users/lbalkin/Desktop/CEE4530_balkin-master/Environmental_Processes_Analysis.py:264: RuntimeWarning: invalid value encountered in sqrt
  return (Pe/(4*np.pi*t))**(0.5)*np.exp((-Pe*((1-t)**2))/(4*t))

We think the solver needs constraints on it so it does not try to take in a negative time or Peclet number.

**Comment by fletchapin** [comment]
@leahbalkin I added bounds to the solver function in the EPA_reactor branch so you could use that version until Monroe pulls the branch to master.

If you're working on a local version of EPA you can just change line 368 to:
```popt, pcov = curve_fit(Tracer_AD_Pe, t_seconds, C_unitless, p0, bounds=(0,inf))```

**Comment by JonathanDavidHarris** [comment]
So I tried running the code with the bounds, and it's giving me errors.

**Comment by fletchapin** [comment]
@JonathanDavidHarris What's the error?

**Comment by JonathanDavidHarris** [comment]
Sorry! It says name 'inf' is not defined.

**Comment by fletchapin** [comment]
Whoops... It should be "np.inf" rather than just "inf" in the bounds. I think it will work if you try that

**Comment by fletchapin** [comment]
The master branch hasn't been updated yet but the EPA_updates branch should hopefully be working now
