### ISSUE TITLE
Problem running function in EPA code

### ISSUE THREAD

**Issue by ak694** [monroews/CEE4530#56]
When I try to run the Tracer_CMFR_N function from EPA.py, I end up getting an error that says 'float' object has no attribute 'exp' and I am unsure what that means. All my inputs are dimensionless

**Comment by fletchapin** [comment]
@ak694 I think the problem might be the (dtype of your input array)[https://stackoverflow.com/questions/18557337/numpy-attributeerror-float-object-has-no-attribute-exp].

For your array inputs, e.g. if ```X``` were an array, try:

```X = X.astype(float)```
