### ISSUE TITLE
Clarification/Confirmation on functions we use in Question 4

### ISSUE THREAD

**Issue by Megan-McE** [monroews/CEE4530#59]
Just to clarify:

If our baffle round more closely resembles a CMFR, we use the EPA.E_CMFR_N(t, N) function where the N input is the N given to us from the modeling in part 2. Do we round this N/does it have to be an integer?

If our baffle round more closely resembles a AD, we use the EPA.E_Advective_Dispersion(t, Pe) function where Pe is the value computed in the modeling in question 2. We do not have to round the Pe value at all, correct?

Just checking! Thanks!

**Comment by fletchapin** [comment]
@Megan-McE I believe this is correct. @monroews can you confirm?

**Comment by monroews** [comment]
Sorry I am weighing in too late! I wouldn't round the N because the estimated N suggests that perhaps all of the CMFRs weren't the same volume and thus the system can't be modeled as an integer number of identical reactors.
