### ISSUE TITLE
When are office hours

### ISSUE THREAD

**Issue by Galantino** [monroews/CEE4530#6]
I'm trying to find an email or on confluence and can't find this info

**Comment by cc2467** [comment]
Tuesday 5:30-6:30 and Thursday 7-8 but we are most likely discontinuing OH in favor of using Github issues.

**Comment by BenGassaway** [comment]
Have office hours been cancelled for this week? If not, where should we find you guys? Thank you!

**Comment by jillianwhiting** [comment]
We will have them tonight only in the lab
