### ISSUE TITLE
Extend the lab due date until Friday?

### ISSUE THREAD

**Issue by Megan-McE** [monroews/CEE4530#63]
@monroews you're a reasonable person who makes good decisions

**Comment by fletchapin** [comment]
We'll discuss it and get back to you, for now expect it to be due on Wednesday

**Comment by monroews** [comment]
I've extended the aeration lab due date until Thursday. We can discuss in lab on Wednesday. Friday is when the proposal is due and so I'd rather not extend the aeration lab until Thursday

**Comment by ak694** [comment]
We are all currently in class waiting for you Monroe...

**Comment by monroews** [comment]
hmmmm.
Sorry about this.
I intended to cancel class today. I forgot to send the email. Aargh.



Monroe Weber-Shirk

AguaClara <http://aguaclara.cornell.edu/> at Cornell
Civil and Environmental Engineering <http://www.cee.cornell.edu/>
Cornell University <http://www.cornell.edu/>
Hollister Hall 265
(607) 216-8445
<http://aguaclara.cornell.edu/>

**Comment by ak694** [comment]
Get well soon, Monroe!
