### ISSUE TITLE
Aerobic Sludge is Frozen

### ISSUE THREAD

**Issue by hispanicberniebro** [monroews/CEE4530#67]
Two of the nutrient removal groups met at the regular class time today to begin running experiments with synthetic wastewater and aerobic sludge. However, both bottles with aerobic sludge were frozen completely and we had dialed down the freezer at its highest setting (7) to the middle setting (4). We are not entirely sure whether the aerobic sludge is usable for the future.

**Comment by monroews** [comment]
New activated sludge sample is in the refrigerator in the lab.
