### ISSUE TITLE
"No kernel for grammar GitHub Markdown found"

### ISSUE THREAD

**Issue by JonathanDavidHarris** [monroews/CEE4530#7]
<img width="479" alt="screen shot 2018-02-13 at 11 15 38 am" src="https://user-images.githubusercontent.com/35547043/36160564-7fe136fa-10af-11e8-8e9f-5c68fd3e9338.png">

I got this error while trying to run python today. Has anyone experienced this before and how to possibly fix it? Thanks.

**Comment by jillianwhiting** [comment]
I have seen two possible fixes for this issue. 

1. Your cursor is in or highlighting non-python code that cannot be run. (You also should not highlight the ```python or ``` part of the code as that does not run either)
2. Atom needs to be fully quit and restarted a few times and then it works. (Don't know why this helps but it does)

**Comment by monroews** [comment]
You will get this error if you have your cursor in markdown text and press shift enter. 
Those commands are interpreted by atom as wanting to execute a kernel of code (like python) and markdown isn't "executed" that way.

**Comment by jdh345** [comment]
Interesting, so I got it to work now. I had written an equation right above my python code, and I don't think markdown liked that which is why I was getting the errors. Once I removed the equation, it worked fine. Thanks guys!
