### ISSUE TITLE
Python Tutorial Latex

### ISSUE THREAD

**Issue by lw583** [monroews/CEE4530#77]
For the question "Show the linear regression equation that you obtained using latex.", is there a way for me to write my variables "slope" and "intercept" and have the values show instead of typing them out directly in markdown? For example, I want to be able to type "slope" and have it show up as 15.88 in LateX. Thanks!

**Comment by monroews** [comment]
This is precisely one of my big complaints about the markdown environment.  I don't like broken dependency and would like the report to update when an input is changed and the code is run again. Unfortunately that isn't how markdown works and we haven't created a "best practice" yet for how to discuss calculated results in markdown. 

For now, copy and paste is the best option I know. Happy to hear other ideas!
