### ISSUE TITLE
Data points for graph

### ISSUE THREAD

**Issue by lw583** [monroews/CEE4530#81]
Q2 says to "Remove data points from the graph that are outside of the linear region". If our points are only linear from 20-200 mg/L, should we still keep 0-10 because four data points is not enough? Or should we just use the four that leave it linear? Thanks.

**Comment by monroews** [comment]
I'd need to see your graph, but the absorbance is expected to go nonlinear for high absorbance values. At low absorbance values it is expected to be linear but noisy. Are you sure that the 100 and 200 mg/L are on the same line as the points at lower concentrations?

**Comment by lw583** [comment]
Apologies, I meant that we wanted to plot 2, 5, 10, 20 which are linear but ignore 0 and 1. My question was whether 4 data points would be too little. Thanks!

**Comment by monroews** [comment]
You could try it both ways. I'd expected the slope and intercept to be very similar and the correlation coefficient to also be similar. This is because the 0,1,2 data points should be almost on top of each other.
