### ISSUE TITLE
Extinction Coefficient Calculation

### ISSUE THREAD

**Issue by lw583** [monroews/CEE4530#82]
On Slide 14 of Laboratory_Measurements.pptx, it gives an equation A = εbc with path length of 1cm. Do we just use that value of b = 1cm (and what does it even represent)? Thanks!

**Comment by monroews** [comment]
Great question. The [photometer description](https://monroews.github.io/EnvEngLabTextbook/ProCoDA/ProCoDA.html#photometer-sensor-photometer) in the lab manual gives the path length. It is the length of the path through the sample that the light travels.
