### ISSUE TITLE
AguaClara_Research error (aide_design.shared)

### ISSUE THREAD

**Issue by bl454** [monroews/CEE4530#84]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-133c828aeb23> in <module>
      2 from aguaclara import *
      3 from aguaclara.core.units import unit_registry as u
----> 4 import aguaclara_research.Environmental_Processes_Analysis as EPA
      5 import numpy as np
      6 import matplotlib.pyplot as plt

~\AppData\Roaming\Python\Python37\site-packages\aguaclara_research\Environmental_Processes_Analysis.py in <module>
----> 1 from aide_design.shared.units import unit_registry as u
      2 from scipy import special
      3 from scipy.optimize import curve_fit
      4 import collections
      5 import pandas as pd

ModuleNotFoundError: No module named 'aide_design.shared'

**Comment by monroews** [comment]
Epa is now part of aguaclara.
