### ISSUE TITLE
'Quantity' Object is not Callable

### ISSUE THREAD

**Issue by kla67** [monroews/CEE4530#9]
When trying to use an exponential function, using a number as the input value, I am getting the error stated above. Did anyone experience this with the last pre-lab? I am importing math and setting up my variables and equations the same as my group, but getting an  error that they are not.

**Comment by monroews** [comment]
Can you show your line of code that is causing the problem?
Try using numpy rather than math. Numpy is compatible with pint (units). If you need to use a math function or something from scipy, then you will need to strip off the units before sending the value to the function.
